// src/components/Navigation.tsx
import { useEffect, useRef, useState } from "react";
import { useActiveNote } from "../contexts/ActiveNoteContext";
import { useNoteStore } from "../stores/notes";
import type { Note } from "../types/notes";

function Dropdown({
	notes,
	onSelect,
	onClose,
	onCreateNew,
	onArchive,
}: {
	notes: Note[];
	onSelect: (note: Note) => void;
	onClose: () => void;
	onCreateNew: () => void;
	onArchive: (noteId: string) => void;
}) {
	const dropdownRef = useRef<HTMLDivElement>(null);

	useEffect(() => {
		const handleClickOutside = (event: MouseEvent) => {
			if (
				dropdownRef.current &&
				!dropdownRef.current.contains(event.target as Node)
			) {
				onClose();
			}
		};

		document.addEventListener("mousedown", handleClickOutside);
		return () => document.removeEventListener("mousedown", handleClickOutside);
	}, [onClose]);

	return (
		<div
			ref={dropdownRef}
			className="absolute top-full left-0 mt-1 bg-paper border rounded-md shadow-lg z-10 min-w-48 max-h-64 overflow-y-auto"
		>
			{notes.length === 0 ? (
				<div className="px-3 py-2 text-sm text-gray-500">No other notes</div>
			) : (
				notes.map((note) => (
					<div
						key={note.id}
						className="flex items-center group hover:bg-background transition-colors"
					>
						<button
							type="button"
							className="flex-1 text-left px-3 py-2 text-sm"
							onClick={() => onSelect(note)}
						>
							{note.title}
						</button>
						<button
							type="button"
							className="px-2 py-2 text-gray-400 hover:text-red-500 opacity-0 group-hover:opacity-100 transition-opacity"
							onClick={(e) => {
								e.stopPropagation();
								onArchive(note.id);
							}}
							title="Archive note"
						>
							×
						</button>
					</div>
				))
			)}
			<button
				type="button"
				className="w-full text-left px-3 py-2 text-sm hover:bg-background transition-colors border-t font-medium"
				onClick={onCreateNew}
			>
				+ New note
			</button>
		</div>
	);
}

function Breadcrumb({
	note,
	text,
	active,
	index,
	onDropdownToggle,
	isDropdownOpen,
	dropdownNotes,
	onCreateChild,
	onArchive,
	isEditing,
	editingTitle,
	onEditingTitleChange,
	onStartEditing,
	onSaveTitle,
	onTitleKeyDown,
}: {
	note?: Note;
	text: string;
	active?: boolean;
	index: number;
	onDropdownToggle: (index: number) => void;
	isDropdownOpen: boolean;
	dropdownNotes: Note[];
	onCreateChild: (parentId: string) => void;
	onArchive: (noteId: string) => void;
	isEditing: boolean;
	editingTitle: string;
	onEditingTitleChange: (title: string) => void;
	onStartEditing: (noteId: string, title: string) => void;
	onSaveTitle: () => void;
	onCancelEditing: () => void;
	onTitleKeyDown: (e: React.KeyboardEvent) => void;
}) {
	const { navigateToNote } = useActiveNote();
	const buttonRef = useRef<HTMLButtonElement>(null);

	const handleClick = () => {
		if (note) {
			navigateToNote(note.id);
		}
	};

	const handleArrowClick = () => {
		if (dropdownNotes.length > 0) {
			onDropdownToggle(index);
		} else if (note && active) {
			// Create new child for active note with no children
			onCreateChild(note.id);
		}
	};

	return (
		<div className="relative">
			<div className="rounded">
				{isEditing && note ? (
					<input
						type="text"
						value={editingTitle}
						onChange={(e) => onEditingTitleChange(e.target.value)}
						onKeyDown={onTitleKeyDown}
						onBlur={onSaveTitle}
						className={`bg-transparent border-none outline-none font-mono text-sm px-1 py-0.5 rounded transition hover:bg-[#00000009] ${
							active && "font-bold hover:bg-transparent w-fit"
						}`}
						onFocus={(e) => {
							if (editingTitle.toLowerCase() === "untitled") {
								e.target.select();
							}
						}}
						// biome-ignore lint/a11y/noAutofocus: doesn't work without it
						autoFocus
					/>
				) : (
					<button
						ref={buttonRef}
						type="button"
						className={`rounded px-1 py-0.5 transition hover:bg-[#00000009] ${
							active && "font-bold"
						} ${active ? "cursor-text" : ""}`}
						onClick={
							note && !active
								? handleClick
								: note && active
									? () => onStartEditing(note.id, note.title)
									: undefined
						}
						onDoubleClick={
							note && !active
								? () => onStartEditing(note.id, note.title)
								: undefined
						}
						disabled={!note}
					>
						{text}
					</button>
				)}
				{!isEditing && (
					<button
						type="button"
						className="rounded px-1 py-0.5 transition hover:bg-[#00000009]"
						onClick={handleArrowClick}
						disabled={dropdownNotes.length === 0 && (!note || !active)}
					>
						{dropdownNotes.length === 0 && note && active ? "+" : ">"}
					</button>
				)}
			</div>
			{isDropdownOpen && (
				<Dropdown
					notes={dropdownNotes}
					onSelect={(selectedNote) => {
						navigateToNote(selectedNote.id);
						onDropdownToggle(-2); // Close dropdown
					}}
					onClose={() => onDropdownToggle(-2)}
					onCreateNew={() => {
						if (note) {
							onCreateChild(note.id);
						}
						onDropdownToggle(-2); // Close dropdown
					}}
					onArchive={onArchive}
				/>
			)}
		</div>
	);
}

function Navigation() {
	const { activeNoteId, navigateToNote } = useActiveNote();
	const {
		getNotePath,
		getRootNotes,
		createNewNote,
		updateNoteTitle,
		getChildNotes,
		archiveNote,
	} = useNoteStore();
	const [openDropdownIndex, setOpenDropdownIndex] = useState<number | null>(
		null,
	);
	const [editingNoteId, setEditingNoteId] = useState<string | null>(null);
	const [editingTitle, setEditingTitle] = useState<string>("");

	const path = activeNoteId ? getNotePath(activeNoteId) : [];

	const handleDropdownToggle = (index: number) => {
		if (index === -2) {
			// Special case for closing dropdown
			setOpenDropdownIndex(null);
		} else {
			setOpenDropdownIndex(openDropdownIndex === index ? null : index);
		}
	};

	const handleRootDropdownToggle = () => {
		setOpenDropdownIndex(openDropdownIndex === -1 ? null : -1);
	};

	const handleCreateChild = async (parentId: string | null) => {
		const newNoteId = await createNewNote(parentId);
		if (newNoteId) {
			navigateToNote(newNoteId);
		}
	};

	const getChildNotesForDropdown = (index: number): Note[] => {
		if (index === -1) {
			// Root dropdown - show all root notes
			return getRootNotes();
		}

		if (index >= path.length) return [];

		// Show children of the note at this index
		const noteId = path[index].id;
		return getChildNotes(noteId);
	};

	const startEditingTitle = (noteId: string, currentTitle: string) => {
		setEditingNoteId(noteId);
		setEditingTitle(currentTitle);
	};

	const saveTitle = async () => {
		if (!editingNoteId) return;

		const finalTitle = editingTitle.trim() || "untitled";

		try {
			await updateNoteTitle(editingNoteId, finalTitle);
			setEditingNoteId(null);
			setEditingTitle("");
		} catch (err) {
			console.error("Failed to save title:", err);
		}
	};

	const cancelEditing = () => {
		setEditingNoteId(null);
		setEditingTitle("");
	};

	const handleTitleKeyDown = (e: React.KeyboardEvent) => {
		if (e.key === "Enter") {
			e.preventDefault();
			saveTitle();
		} else if (e.key === "Escape") {
			e.preventDefault();
			cancelEditing();
		}
	};

	const handleArchive = async (noteId: string) => {
		try {
			await archiveNote(noteId);
			// If the archived note was the active note, we might want to navigate away
			if (noteId === activeNoteId) {
				// Navigate to parent or first available note
				const archivedNote = path.find((n) => n.id === noteId);
				if (archivedNote?.parentId) {
					navigateToNote(archivedNote.parentId);
				} else {
					const rootNotes = getRootNotes();
					if (rootNotes.length > 0) {
						navigateToNote(rootNotes[0].id);
					}
				}
			}
		} catch (err) {
			console.error("Failed to archive note:", err);
		}
	};

	if (!activeNoteId) {
		return (
			<nav className="px-2 pb-0.5">
				<div className="flex items-center justify-between">
					<div className="flex items-center font-mono text-sm tracking-tight text-gray-500">
						No note selected
					</div>
				</div>
			</nav>
		);
	}

	return (
		<nav className="px-2 pb-0.5 bg-background w-screen z-20 select-none">
			<div className="flex items-center justify-between">
				<div className="flex items-center font-mono text-sm tracking-tight">
					{/* Root dropdown */}
					<div className="relative">
						<button
							type="button"
							className="rounded px-1 py-0.5 transition hover:bg-[#00000009]"
							onClick={handleRootDropdownToggle}
						>
							&gt;
						</button>
						{openDropdownIndex === -1 && (
							<Dropdown
								notes={getRootNotes()}
								onSelect={(selectedNote) => {
									navigateToNote(selectedNote.id);
									handleDropdownToggle(-2);
								}}
								onClose={() => handleDropdownToggle(-2)}
								onCreateNew={() => {
									handleCreateChild(null);
									handleDropdownToggle(-2);
								}}
								onArchive={handleArchive}
							/>
						)}
					</div>

					{path.map((note, index) => (
						<Breadcrumb
							key={note.id}
							note={note}
							text={note.title}
							active={note.id === activeNoteId}
							index={index}
							onDropdownToggle={handleDropdownToggle}
							isDropdownOpen={openDropdownIndex === index}
							dropdownNotes={getChildNotesForDropdown(index)}
							onCreateChild={handleCreateChild}
							onArchive={handleArchive}
							isEditing={editingNoteId === note.id}
							editingTitle={editingTitle}
							onEditingTitleChange={setEditingTitle}
							onStartEditing={startEditingTitle}
							onSaveTitle={saveTitle}
							onCancelEditing={cancelEditing}
							onTitleKeyDown={handleTitleKeyDown}
						/>
					))}
				</div>
			</div>
		</nav>
	);
}

export default Navigation;

// crates/frontend/src/components/Navigation.tsx
import { createSignal, For, Show, createEffect } from "solid-js";
import { useNotes } from "../api";
import { commands } from "../api/commands";
import { getPathTitle } from "../utils/paths";
import { InputModal } from "./InputModal";
import type { NoteMetadata } from "../types";

const MAX_TITLE_LENGTH = 18;

function truncateTitle(
  title: string,
  maxLength: number = MAX_TITLE_LENGTH,
): string {
  if (title.length <= maxLength) {
    return title;
  }
  return title.slice(0, maxLength).trimEnd() + "…";
}

function CrumbButton(props: {
  content: NoteMetadata[];
  path: string;
  onRefresh?: () => void;
  children: string;
}) {
  let buttonRef: HTMLButtonElement | undefined;
  let dialogRef: HTMLDialogElement | undefined;

  const notes = useNotes();
  const [showModal, setShowModal] = createSignal(false);

  // Sort notes by modification time (most recent first)
  const sortedContent = () => {
    return [...props.content].sort((a, b) => b.modified - a.modified);
  };

  const handleClick = () => {
    if (dialogRef && buttonRef) {
      const rect = buttonRef.getBoundingClientRect();
      dialogRef.style.top = `${rect.top}px`;
      dialogRef.style.left = `${rect.left}px`;
      dialogRef.showModal();
    }
  };

  const handleDialogClick = (e: MouseEvent) => {
    if (e.target === dialogRef) {
      dialogRef?.close();
    }
  };

  const createNewNote = async (title: string) => {
    const newPath = props.path ? `${props.path}/${title}` : title;
    try {
      const newNote = await commands.createNote(newPath);
      dialogRef?.close();
      setShowModal(false);
      notes.setCurrentPath(newNote.path);
      props.onRefresh?.();
    } catch (err) {
      console.error("Failed to create note:", err);
      alert(`Failed to create note: ${err}`);
    }
  };

  const handleArchive = async (notePath: string) => {
    try {
      await commands.archiveNote(notePath);
      if (notes.currentPath() === notePath) {
        const segments = notePath.split("/");
        segments.pop();
        notes.setCurrentPath(segments.join("/"));
      }
      props.onRefresh?.();
    } catch (err) {
      console.error("Failed to archive:", err);
      alert(`Failed to archive: ${err}`);
    }
  };

  return (
    <>
      <InputModal
        showModal={showModal()}
        onSubmit={createNewNote}
        placeholder="untitled"
        onClose={() => setShowModal(false)}
      />
      <button
        ref={buttonRef}
        class="hover:bg-button-hover rounded px-2"
        onClick={handleClick}
      >
        {props.children}
      </button>
      <dialog
        ref={dialogRef}
        class="bg-paper text-text-muted max-w-[200px] min-w-[160px] translate-x-8 rounded-lg border outline-none *:border-b backdrop:bg-transparent *:last:border-0"
        onClick={handleDialogClick}
      >
        <For each={sortedContent()}>
          {(note) => (
            <div class="group relative">
              <button
                onClick={() => {
                  notes.setCurrentPath(note.path);
                  dialogRef?.close();
                  // console.log("closed");
                }}
                class="hover:bg-button-bg w-full px-2 py-1.5 text-left outline-none select-none"
                title={getPathTitle(note.path)}
              >
                {truncateTitle(getPathTitle(note.path))}
              </button>
              <div class="absolute right-2 z-50 hidden h-full items-center group-hover:inline-flex">
                <button
                  class="hover:text-red p-0.5 hover:opacity-80"
                  onClick={() => handleArchive(note.path)}
                >
                  ×
                </button>
              </div>
            </div>
          )}
        </For>
        <button
          onClick={() => {
            setShowModal(true);
            dialogRef?.close();
          }}
          class="bg-button-bg w-full px-2 py-2 text-left outline-none select-none"
        >
          New note +
        </button>
      </dialog>
    </>
  );
}

function Breadcrumb(props: { item: NoteMetadata; isActive: boolean }) {
  const notes = useNotes();
  const [children, setChildren] = createSignal<NoteMetadata[]>([]);
  const [refreshKey, setRefreshKey] = createSignal(0);
  const [isEditing, setIsEditing] = createSignal(false);
  const [editTitle, setEditTitle] = createSignal("");

  createEffect(() => {
    refreshKey(); // Track refresh key
    commands.getChildren(props.item.path).then(setChildren);
  });

  const handleCreateNote = async () => {
    const newPath = `${props.item.path}/untitled`;
    try {
      await commands.createNote(newPath);
      notes.setCurrentPath(newPath);
      setRefreshKey((k) => k + 1);
    } catch (err) {
      console.error("Failed to create note:", err);
      alert(`Failed to create note: ${err}`);
    }
  };

  const [inputRef, setInputRef] = createSignal<HTMLInputElement | null>(null);

  const handleClick = () => {
    if (props.isActive) {
      // Enter edit mode
      setEditTitle(getPathTitle(props.item.path));
      setIsEditing(true);
      inputRef()!.focus();
    } else {
      // Navigate
      notes.setCurrentPath(props.item.path);
    }
  };

  const handleRename = async () => {
    const newTitle = editTitle().trim() || "untitled";
    const currentTitle = getPathTitle(props.item.path);

    if (newTitle !== currentTitle) {
      const parentPath = props.item.path.split("/").slice(0, -1).join("/");
      const newPath = parentPath ? `${parentPath}/${newTitle}` : newTitle;

      try {
        await commands.renameNote(props.item.path, newPath);
        notes.setCurrentPath(newPath);
      } catch (err) {
        console.error("Failed to rename:", err);
        alert(`Failed to rename: ${err}`);
      }
    }
    setIsEditing(false);
  };

  return (
    <>
      <Show
        when={isEditing()}
        fallback={
          <button
            class={`hover:bg-button-hover rounded px-2 ${props.isActive ? "font-bold" : ""}`}
            onClick={handleClick}
          >
            {getPathTitle(props.item.path)}
          </button>
        }
      >
        <input
          type="text"
          value={editTitle()}
          onInput={(e) => setEditTitle(e.currentTarget.value)}
          onBlur={handleRename}
          onKeyDown={(e) => {
            if (e.key === "Enter") handleRename();
            if (e.key === "Escape") setIsEditing(false);
          }}
          class="bg-transparent px-2 outline-none"
          ref={setInputRef}
        />
      </Show>
      <Show when={!isEditing()}>
        <Show
          when={children().length > 0}
          fallback={
            <button
              class="hover:bg-button-hover rounded px-2"
              onClick={handleCreateNote}
            >
              +
            </button>
          }
        >
          <CrumbButton
            content={children()}
            path={props.item.path}
            onRefresh={() => setRefreshKey((k) => k + 1)}
          >
            {">"}
          </CrumbButton>
        </Show>
      </Show>
    </>
  );
}

function RootCrumb() {
  const [rootNotes, setRootNotes] = createSignal<NoteMetadata[]>([]);
  const [refreshKey, setRefreshKey] = createSignal(0);

  createEffect(() => {
    refreshKey(); // Track refresh key
    commands.getRootNotes().then(setRootNotes);
  });

  return (
    <CrumbButton
      content={rootNotes()}
      path=""
      onRefresh={() => setRefreshKey((k) => k + 1)}
    >
      {">"}
    </CrumbButton>
  );
}

export function Navigation() {
  const notes = useNotes();
  const [items, setItems] = createSignal<NoteMetadata[]>([]);

  createEffect(() => {
    const path = notes.currentPath();
    if (path) {
      commands.getAncestors(path).then(setItems);
    } else {
      setItems([]);
    }
  });

  return (
    <nav class="bg-background fixed top-0 left-0 z-10 flex h-8 w-full items-center px-4 pb-2 font-mono text-sm select-none">
      <div class="flex flex-1">
        <RootCrumb />
        <For each={items()}>
          {(item, index) => {
            const isActive = () => index() === items().length - 1;
            return <Breadcrumb item={item} isActive={isActive()} />;
          }}
        </For>
      </div>
      <div class="ml-4 flex gap-1">
        <button
          class="hover:bg-button-hover rounded px-2 disabled:cursor-not-allowed disabled:opacity-30"
          onClick={() => notes.goBack()}
          disabled={!notes.canGoBack()}
          title="Go back"
        >
          ←
        </button>
        <button
          class="hover:bg-button-hover rounded px-2 disabled:cursor-not-allowed disabled:opacity-30"
          onClick={() => notes.goForward()}
          disabled={!notes.canGoForward()}
          title="Go forward"
        >
          →
        </button>
      </div>
    </nav>
  );
}
